//==================================================
//     Outputs that match the input variables
//==================================================
output "cidr_sets_ipv4" {
  description = "The value of the `cidr_sets_ipv4` input variable."
  value       = var.cidr_sets_ipv4
}

//==================================================
//       Outputs generated by this module
//==================================================
output "merged_cidr_sets_ipv4" {
  description = "The merged CIDR sets."
  value       = local.final_cidrs_ipv4
}
output "merged_cidr_sets_ipv4_with_meta" {
  description = "The merged CIDR sets, with additional metadata including the CIDRs that were merged into this one and additional IP data."
  value       = local.final_cidrs_ipv4_with_meta
}

//==================================================
//             Debugging outputs
//==================================================
# output "_01_cidrs_distinct" {
#   value = local.cidrs_distinct
# }
# output "_02_cidrs_with_first_last" {
#   value = local.cidrs_with_first_last
# }
# output "_03_cidrs_with_first_last_decimal" {
#   value = local.cidrs_with_first_last_decimal
# }
# output "_04_cidrs_largest_only" {
#   value = local.cidrs_largest_only
# }
# output "_05_cidrs_with_sort_keys" {
#   value = local.cidrs_with_sort_keys
# }
# output "_06_cidrs_keys_sorted" {
#   value = local.cidrs_keys_sorted
# }
# output "_07_cidrs_sorted" {
#   value = local.cidrs_sorted
# }
# output "_08_contiguous_cidr_sets_tmp" {
#   value = local.contiguous_cidr_sets_tmp
# }
# output "_09_contiguous_cidr_sets_flags" {
#   value = local.contiguous_cidr_sets_flags
# }
# output "_10_contiguous_cidr_sets" {
#   value = local.contiguous_cidr_sets
# }
# output "_11_contiguous_cidr_meta" {
#   value = local.contiguous_cidrs_meta
# }
# output "_12_contiguous_cidr_meta_2" {
#   value = local.contiguous_cidrs_meta_2
# }
# output "_13_contiguous_cidr_meta_3" {
#   value = local.contiguous_cidrs_meta_3
# }
# output "_14_contiguous_cidr_meta_4" {
#   value = local.contiguous_cidrs_meta_4
# }
# output "_15_merged_cidrs" {
#   value = local.merged_cidrs
# }
